# Generated by Django 5.0.6 on 2024-07-10 10:17

import server.models
import server.validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0002_category_icon"),
    ]

    operations = [
        migrations.AddField(
            model_name="channel",
            name="banner",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=server.models.server_banner_upload_path,
                validators=[server.validator.validate_image_file_extension],
            ),
        ),
        migrations.AddField(
            model_name="channel",
            name="icon",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=server.models.server_icon_upload_path,
                validators=[
                    server.validator.validate_icon_image_size,
                    server.validator.validate_image_file_extension,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="icon",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=server.models.category_icon_upload_path,
                validators=[
                    server.validator.validate_icon_image_size,
                    server.validator.validate_image_file_extension,
                ],
            ),
        ),
    ]
